name: tic_quiz
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"

flutter_icons:
  ios: true
  andriod: true
  image_path: "assets/Logo2.png"

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/Logo.png
    - assets/Logo2.png
    - assets/welcome.png

  uses-material-design: true

