name: tic_quiz
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  pin_code_fields: ^8.0.0
  curved_navigation_bar: ^1.0.6
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.3.0
  provider: ^6.1.5
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.2.1
  image_picker: ^1.0.0
  firebase_storage: ^12.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/Logo.png
    - assets/welcome.png
    - assets/google.png
    - assets/google_logo.png
    - assets/Logo_Android12.png

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/Logo.png"

flutter_native_splash:
  ios: true
  android: true
  image: "assets/Logo.png"
  color: "#FFFFFF"
  android_12:
    color: "#FFFFFF"
    image: "assets/Logo_Android12.png"